let car = "tesla"
console.log("is car not equal to tesla result",car =="BMW" )
console.log("is car equal to tesla result",car == "BRV")
console.log("is car equal to tesla result",car == "tesla")
console.log("is car not equal to BRV result",car == "mercedes")
console.log("is car equal to tesla result",car !== "ford")
console.log("is car equal to tesla result",car == "supra")
console.log("is car equal to tesla result",car == "sprotage")
console.log("is car equal to tesla result",car !== "maclern")
console.log("is car equal to tesla result",car !== "city")
console.log("is car equal to tesla result",car !== "rangerover")
